name: Denná aktualizácia dát
on:
  schedule:
    - cron: '0 8 * * *' # Každé ráno o 8:00
  workflow_dispatch: # Možnosť spustiť ručne

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install axios
      - name: Run update script
        run: node update_data.js
        env:
          API_NINJAS_KEY: ${{ secrets.API_NINJAS_KEY }}
      
      - name: Commit changes
        run: |
          git config --global user.name 'Data Bot'
          git config --global user.email 'bot@noreply.com'
          git add data.json
          git commit -m "Automatická aktualizácia dát" || echo "Žiadne zmeny"
          git push
          
      - name: Send Email Notification
        if: success() # Tu by sa pridala podmienka, ak sa zmenili dáta
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Ekonomické dáta SR - Zmena
          body: Boli zverejnené nové ekonomické dáta. Skontroluj web.
          to: tomanekk.ivan@gmail.com
          from: Ekonomický Bot
